const products = [
  {id:1,name:'Soft Utility Overshirt',category:'Layering',style:'Utility',size:'M',price:18,condition:'Good',color:'Faded olive',visual:'visual-1',icon:'01',description:'A fictional lightweight layer with a relaxed shape and everyday styling potential.',details:'Placeholder item · measurements and flaws to be added'},
  {id:2,name:'Ribbed Everyday Tee',category:'Casual',style:'Minimal',size:'S',price:10,condition:'Good',color:'Cream',visual:'visual-2',icon:'02',description:'A fictional staple tee for simple outfits, classes, and weekends.',details:'Placeholder item · measurements and flaws to be added'},
  {id:3,name:'Contrast Stitch Sweatshirt',category:'Casual',style:'Y2K-inspired',size:'L',price:16,condition:'Fair',color:'Brick red',visual:'visual-3',icon:'03',description:'A fictional casual sweatshirt with a little extra visual detail.',details:'Placeholder item · measurements and flaws to be added'},
  {id:4,name:'Lightweight Nylon Jacket',category:'Layering',style:'Utility',size:'XL',price:22,condition:'Good',color:'Slate blue',visual:'visual-4',icon:'04',description:'A fictional practical layer for changing weather and everyday errands.',details:'Placeholder item · measurements and flaws to be added'},
  {id:5,name:'Pleated Everyday Trouser',category:'Vintage-inspired',style:'Minimal',size:'S',price:20,condition:'Good',color:'Warm khaki',visual:'visual-5',icon:'05',description:'A fictional trouser silhouette designed for repeat wear and easy pairing.',details:'Placeholder item · measurements and flaws to be added'},
  {id:6,name:'Cropped Knit Cardigan',category:'Vintage-inspired',style:'Y2K-inspired',size:'XS',price:14,condition:'Fair',color:'Dusty lilac',visual:'visual-6',icon:'06',description:'A fictional knit layer with a vintage-inspired shape and soft color.',details:'Placeholder item · measurements and flaws to be added'}
];

function productCard(product){return `<article class="product-card"><div class="product-visual ${product.visual}" aria-label="Placeholder image for ${product.name}"><span class="visual-icon">${product.icon}</span></div><div class="product-info"><div class="product-top"><h3>${product.name}</h3><span class="product-price">$${product.price}</span></div><div class="product-meta"><span>${product.category}</span><span>·</span><span>Size ${product.size}</span><span>·</span><span>${product.condition}</span></div><p class="product-description">${product.description}</p><div class="product-actions"><small>${product.details}</small><button class="small-button" data-product="${product.id}">Details</button></div></div></article>`}

function renderProducts(target, list){if(!target)return;target.innerHTML=list.map(productCard).join('');target.querySelectorAll('[data-product]').forEach(button=>button.addEventListener('click',()=>showProduct(Number(button.dataset.product))))}
function showProduct(id){const p=products.find(item=>item.id===id);if(!p)return;let modal=document.querySelector('#product-modal');if(!modal){modal=document.createElement('div');modal.id='product-modal';modal.className='modal';document.body.appendChild(modal)}modal.innerHTML=`<div class="modal-card" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button class="modal-close" aria-label="Close details">×</button><div class="product-visual ${p.visual}"><span class="visual-icon">${p.icon}</span></div><div class="modal-content"><p class="eyebrow">Fictional sample listing</p><h2 id="modal-title">${p.name}</h2><p>${p.description}</p><dl class="detail-list"><div><dt>Price</dt><dd>$${p.price} placeholder</dd></div><div><dt>Size</dt><dd>${p.size} · measurements to be added</dd></div><div><dt>Condition</dt><dd>${p.condition} · visible flaws to be added</dd></div><div><dt>Color</dt><dd>${p.color}</dd></div></dl><a class="button primary" href="contact.html">Ask about this item <span>→</span></a></div></div>`;modal.classList.add('show');modal.querySelector('.modal-close').focus();modal.querySelector('.modal-close').addEventListener('click',()=>modal.remove());modal.addEventListener('click',e=>{if(e.target===modal)modal.remove()})}

function initShop(){const target=document.querySelector('#shop-products');if(!target)return;const category=document.querySelector('#category-filter'),size=document.querySelector('#size-filter'),style=document.querySelector('#style-filter'),sort=document.querySelector('#sort-filter'),count=document.querySelector('#results-count'),empty=document.querySelector('#empty-state');const params=new URLSearchParams(location.search);if(params.get('category'))category.value=params.get('category');function update(){let list=products.filter(p=>(category.value==='All'||p.category===category.value)&&(size.value==='All'||p.size===size.value)&&(style.value==='All'||p.style===style.value));if(sort.value==='price-low')list.sort((a,b)=>a.price-b.price);if(sort.value==='price-high')list.sort((a,b)=>b.price-a.price);if(sort.value==='name')list.sort((a,b)=>a.name.localeCompare(b.name));count.textContent=`${list.length} sample ${list.length===1?'piece':'pieces'}`;empty.hidden=list.length>0;renderProducts(target,list)}[category,size,style,sort].forEach(el=>el.addEventListener('change',update));document.querySelector('#clear-filters').addEventListener('click',()=>{category.value='All';size.value='All';style.value='All';sort.value='featured';update()});update()}

function initForms(){document.querySelectorAll('[data-demo-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const message=form.querySelector('.form-message');if(message){message.textContent=form.classList.contains('contact-form')?'Thanks—this demo message is ready, but no inbox is connected yet.':'Thanks for joining the placeholder list.'}form.reset()}))}
function initMenu(){const button=document.querySelector('.menu-toggle'),nav=document.querySelector('#site-nav');if(!button||!nav)return;button.addEventListener('click',()=>{const open=nav.classList.toggle('open');button.setAttribute('aria-expanded',String(open))})}
document.addEventListener('DOMContentLoaded',()=>{renderProducts(document.querySelector('#featured-products'),products.slice(0,3));initShop();initForms();initMenu()});
